### PR TITLE
quick grammar updates

### PR DESCRIPTION
**Pull request by byronbytes**
If theres anything I missed I'll add it / update it, but first I need direct reviewal from you.

### CODE REVIEW

**Review by hxr404 — APPROVED** [review]
Thanks a lot for the PR!
Looks good so far

**Comment by byronbytes** [comment]
Alright, now that I have approval I'm going to see if theres any more grammar errors and fix them

**Comment by hxr404** [comment]
Yeah, there are probably still a bunch of mistakes, back then when I started this project I used the GitHub UI (with automatic german spell-checker enabled...) and besides I wasn't really good at speaking English (I still am not good xD)

So yea

**Comment by hxr404** [comment]
Sorry closed by accident :/

**Comment by byronbytes** [comment]
It's alright! I understand, I'll also help out with the Oxygen documents as well if you want.

**Review by hxr404 — APPROVED** [review]

**Comment by hxr404** [comment]
> It's alright! I understand, I'll also help out with the Oxygen documents as well if you want.

That would be super awesome!
Its on my To-Do-List for quite some time now, seems like I was successfully procrastinating here...

**Pull request merged**
