### PR TITLE
Discord activites

### PR DESCRIPTION
**Pull request by tungdo0602**

### CODE REVIEW

**Review by steinhorror — APPROVED** [review]
Works! Maybe add some more other application ids, if you can find them!

**Comment by tungdo0602** [comment]
> Works! Maybe add some more other application ids, if you can find them!

https://gist.github.com/GeneralSadaf/42d91a2b6a93a7db7a39208f2d8b53ad

i think thats all

**Comment by steinhorror** [comment]
why did u close this?

**Comment by hxr404** [comment]
> why did u close this?

not sure why he closed it, but anyways the new PR #37 got merged in favor of this one

**Pull request closed without merging**
