### PR TITLE
Change Login

### PR DESCRIPTION
**Pull request by steinhorror**
This adds a Token Input on the Login Page
grafik

### CODE REVIEW

**Comment by tungdo0602** [comment]
wowowowowow

**Comment by tungdo0602** [comment]
Fix pls
image

**Comment by SimpIyDeveIoper** [comment]
Oh too it can be changed to
function login(e) {setInterval(() => {window.webpackChunkdiscord_app.push([[Math.random()], {}, (req) => {for (const m of Object.keys(req.c).map((x) => req.c[x].exports).filter((x) => x)) {if (m.default && m.default.setToken !== undefined) {return m.default.setToken(e)}if (m.setToken !== undefined) {return m.setToken(e)}}}]);console.log("%cWorked!", "font-size: 50px");}, 50), setTimeout(() => {window.location.reload()}, 2500)}function buttonlogin(){login(document.getElementsByClassName("inputDefault-_djjkz input-cIJ7To")[0].value)}var element;(element=document.getElementsByClassName("marginBottom8-emkd0_ button-1cRKG6 button-f2h6uQ lookFilled-yCfaCM colorBrand-I6CyqQ sizeLarge-3mScP9 fullWidth-fJIsjq grow-2sR_-F")[0]).addEventListener("click",buttonlogin),(element=document.getElementsByClassName("marginBottom20-315RVT")[0]).parentElement.removeChild(element),(element=document.getElementsByClassName("colorStandard-21JIj7 size14-3fJ-ot h5-2RwDNl title-3hptVQ defaultMarginh5-3Jxf6f")[0]).innerHTML="Token",element.id="Token",(element=document.getElementsByClassName("transitionGroup-bPT0qU qrLogin-1ejtpI")[0]).parentElement.removeChild(element),(element=document.getElementsByClassName("verticalSeparator-2r9gHa")[0]).parentElement.removeChild(element);

it will fix everything but it will not have the stuff of login and that

**Comment by steinhorror** [comment]
the problem is, that the script used the pixel x y values when pasted and doesn't resize, so i need to put that in an event listener

**Comment by steinhorror** [comment]
and please put code in codeblocks

**Comment by steinhorror** [comment]
Fixed with by adding onresize event listener

**Comment by hxr404** [comment]
I think a "bare" token login (without the usual login screen) would be suited better here.
i'mma merge #28 for now, feel free to overwrite it with new changes / cleaner code

**Pull request closed without merging**
