### PR TITLE
Nitro Simulator

### PR DESCRIPTION
**Pull request by afkvido**
Adding the Nitro Simulator by tungdo0602:

https://github.com/tungdo0602/Discord-Nitro-Simulator

### CODE REVIEW

**Comment by hxr404** [comment]
1. I won't add code written by others into my projects (unless I they explicitly allow me to do so)
2. It's easily detectable and doesn't even add any features (doesn't even display a Nitro subscription)
3. Everything that this "Nitro Simulator" does is already included in Discord Oxygen
4. I don't want that people get confused and think that this script will give them any kind of Nitro perks cuz it does not.

**Comment by afkvido** [comment]
ok

<h6>but discord oxygen is paid lmao</h6>

**Comment by hxr404** [comment]
> but discord oxygen is paid lmao

There will be a free tier. But amyways, Discord Oxygen being paid doesn't change anything about the other reasons why this PR won't be merged.

**Comment by afkvido** [comment]
oh well, thank you for reviewing the PR anyways!

**Pull request closed without merging**
