### PR TITLE
Fix Flag Number And Update Command

### PR DESCRIPTION
**Pull request by Shayshon**

### CODE REVIEW

**Comment by hxr404** [comment]
Why did you change the flag number? 410575 just includes all badges shown in your screenshot, wheras -1 includes every badge, including those that will be added in the future.
Also the old command still works perfectly fine for me (even on canary)

oh and I prefer showing hxr404 in the screenshots instead of your account (to not confuse users)

**Comment by Shayshon** [comment]
> Why did you change the flag number? 410575 just includes all badges shown in your screenshot, wheras -1 includes every badge, including those that will be added in the future.
> Also the old command still works perfectly fine for me (even on canary)
> 
> oh and I prefer showing hxr404 in the screenshots instead of your account (to not confuse users)

Hey- sorry I couldn't respond right away, I had no internet. -1 (while it will give your account all flags) is a bit risky because it will literally give your account all available flags including (but not limited to) an internal application flag and a "hey discord sent you a message, look at it" flag. If discord ever adds anymore flags, it could raise suspicion on the users account. That's why it's a good idea to be specific about the flag number. The command you have listed (while working) is pasted twice and not formatted very well. And I just put that image in as a placeholder... feel free to use any other image.

**Comment by hxr404** [comment]
> The command you have listed (while working) is pasted twice

not exactly. One of them is flags and the second one public_flags. Flags only works on your own Account (If you would insert any other userid then yours, it wouldn't work) and public flags works on both, thats why I included them.

<br>

>  it could raise suspicion on the users account.

If someone has the "Staff" flag, I think it would already be suspicious enough...
But because the modification is client-side, they wouldn't notice and it doesn't make a difference

**Comment by hxr404** [comment]
> and not formatted very well.

well yeah thats a good point....
But your code isn't the same as my code, I think un-minified it would look more like this:
```js
Object.values(webpackJsonp.push([
    [], {
        ['']: (_, e, r) => {
            e.cache = r.c
        }
    },
    [
        ['']
    ]
]).cache).find(m => m.exports && m.exports.default && m.exports.default.getCurrentUser !== void 0).exports.default.getCurrentUser().flags = -1

Object.values(webpackJsonp.push([
    [], {
        ['']: (_, e, r) => {
            e.cache = r.c
        }
    },
    [
        ['']
    ]
]).cache).find(m => m.exports && m.exports.default && m.exports.default.getCurrentUser !== void 0).exports.default.getCurrentUser().public_flags = -1
```

**Comment by Shayshon** [comment]
> > and not formatted very well.
> 
> well yeah thats a good point....
> But your code isn't the same as my code, I think un-minified it would look more like this:
> ```js
> Object.values(webpackJsonp.push([
>     [], {
>         ['']: (_, e, r) => {
>             e.cache = r.c
>         }
>     },
>     [
>         ['']
>     ]
> ]).cache).find(m => m.exports && m.exports.default && m.exports.default.getCurrentUser !== void 0).exports.default.getCurrentUser().flags = -1
> 
> Object.values(webpackJsonp.push([
>     [], {
>         ['']: (_, e, r) => {
>             e.cache = r.c
>         }
>     },
>     [
>         ['']
>     ]
> ]).cache).find(m => m.exports && m.exports.default && m.exports.default.getCurrentUser !== void 0).exports.default.getCurrentUser().public_flags = -1
> ```

You pasted it twice, you can also remove most the spaces

**Comment by Shayshon** [comment]
> > The command you have listed (while working) is pasted twice
> 
> not exactly. One of them is flags and the second one public_flags. Flags only works on your own Account (If you would insert any other userid then yours, it wouldn't work) and public flags works on both, thats why I included them.
> 
> <br>
> 
> >  it could raise suspicion on the users account.
> 
> If someone has the "Staff" flag, I think it would already be suspicious enough...
> But because the modification is client-side, they wouldn't notice and it doesn't make a difference

They would definitely notice if a user starts sending random api requests

**Pull request closed without merging**
