### PR TITLE
Added extra information, added an extra script & changed some text

### PR DESCRIPTION
**Pull request by RobinRMC**
This pull request includes the shortened token grabber warning.

Also, please read the commit description.
Thanks! 🙂

### CODE REVIEW

**Review by hxr404 — CHANGES_REQUESTED** [review]
There are merge conflicts, please rebase ontop of the latest commit in main

**Comment by hxr404** [comment]
Actually now that I think of it, this PR doesn't change anything except for f02ebf6. (In case you didn't notice or something, I squash-merged #72)

So better make a new branch (up-to-date with main) and cherry-pick f02ebf6 into that.
(Alternatively wait a few days until I assembled my laptop again and I can cherry-pick it too.)

Anyway, this PR right here doesn't make much sense so closing.

**Comment by hxr404** [comment]
btw
> please don't add commits to my pull requests, but instead push them after merging a pull request. If you add a commit to my pull request, I can't synchronize my fork properly. Thanks! :)

(ignoring the fact that commit msg's aren't the right place for discussing such things)
I didn't add commits to your PR but to the main branch after squashing your commits. (see `git log upstream`, assuming your remote tracking this repo is called upstream (afaik the gh default for forks).

Lastly some advice I wish I would've got:
Don't rely on the GitHub UI. The sync thingy can't handle the most basic operations, it WILL mess up your repo. Trust me, don't use it for anything except perhaps ff-merges.
(No, the proprietary nature of Github isn't the only reason I avoid this website and migrated every serious non-discord-related project to GitTea...)

**Comment by RobinRMC** [comment]
Oh, I see now. It said referenced, not added a commit. My fault.

**Comment by RobinRMC** [comment]
How would I go about synchronizing my fork without losing my individual commits?

**Comment by hxr404** [comment]
That's the neat thing about GitHub web:
You don't....

For any serious git related work you really gotta use the cli, there's just no other way.
I mean think of it, how are you even gonna run pre-commit hooks like linters, formatters, etc. on a Web UI?
Centralizing a decentralized system like that wasn't a good idea to begin with.
You can't work with git without having access to git.

Since you don't seem to have a way to access git I'd say I'll just cherry-pick the commit myself as soon as I'm done re-assembling my laptop (which has my gpg keys and github credentials on it)
In the meantime I'd suggest you this https://git-scm.com/book/en/v2 tutorial. Imo it's the best one out there. It quickly got you covered about all the basic stuff you need to know for working with git.
The authors definetly explain better (and more concise) than I ever could how to sync forks.

**Comment by RobinRMC** [comment]
Okay, thanks for providing me help.
Is there a specific reason why you're using squash merge?
(Also, you might've already noticed that I'm not actually a developer. The only Git tool I sometimes use is git-gui. I think that should say enough. 😂 (Yes, I know GitHub Desktop exists.))

**Comment by hxr404** [comment]
> Okay, thanks for providing me help.

np

> Is there a specific reason why you're using squash merge?

Yeah there is a reason. Usually I use a GitFlow based structure, but since this started as a personal collection of scripts for private use, more like a gist instead of a fully-fledged project (I didn't expect this to blow up that much lol) I didn't bother.
But at least I can try making things a little bit more ordered and workable with.
Ten separate commits (of which one is literally "nothing") changing more or less the same thing is really something that doesn't belong into a readable commit history, thus the squash.
Additionally it wouldn't be fair having a single contribution _(actually two, but since you didn't make two PRs I have no way of including that as a separate commit)_ show up as 10 in the stats.

> Also, you might've already noticed that I'm not actually a developer.

Yeah dw, most people here aren't.
(That's also one of the reasons I didn't introduce a proper branching model, contributing guidelines, etc, yet.)

> Yes, I know GitHub Desktop exists.

Honestly, don't even bother, lol
If you read the git book (takes about 30 mins if you are a really quick reader) you'll find the CLI intuitively easier to use and way more powerful (at least in my experience)

**Comment by RobinRMC** [comment]
I understand. Thanks for explaining. 🙂

**Pull request closed without merging**
